# name: api_gptvision deployment

# on:
#     push:
#         branches:
#             - main
#         paths:
#             - 'api_gptvision/**'
#     pull_request:
#         branches:
#             - main
#         paths:
#             - 'api_gptvision/**'
#     workflow_dispatch:

# jobs:
#     build:
#         name: Build
#         runs-on: ubuntu-latest
#         steps:
#             - name: Build
#               run: |
#                   echo "Building..."
#                   cd api_gptvision
#                   npm install
#                   npm run build

#     deploy-production:
#         name: Deploy
#         runs-on: ubuntu-latest
#         environment: 
#             name: production

#         needs: build
#         steps:
#             - name: Repo Checkout
#               uses: actions/checkout@v2
#             - name: Deploy
#               uses: peaceiris/actions-gh-pages@v3
#               with:
#                   SSH_PRIVATE_KEY: ${{ secrets.NODEHOST}}
#                   IMAGE_PATH: ${{ secrets.IMAGE_PATH}}
#                   IMAGE_URL: ${{ secrets.IMAGE_URL}}
#                   OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY}}
#                   PROMPT: ${{ secrets.PROMPT}}
#                   PORTA: ${{ vars.PORTA }}